### ISSUE TITLE
Make CosmosDb client ConnectionPolicy configurable

### ISSUE THREAD

**Issue by lordjeb** [Oriflame/cosmosdb-quartznet#9]
I need to use CosmosDb job store in a global multi writable configuration, which requires adjusting the ConnectionPolicy used to create the DocumentClient. I need to pass in the UseMultipleWriteLocations property on that, and would propose exposing that as a public property of the CosmosDbJobStore.

Seeing in the code that there is already a TODO to make some of those settings configurable, I would propose adding properties to the job store for setting RequestTimeout, MaxConnectionLimit, MaxRetryWaitTimeInSeconds, and MaxRetryAttemptsOnThrottledRequests as well.

**Comment by twhiting** [comment]
@kirilovskii @frantisekjandos have you guys had a chance to look at this issue?

**Comment by twhiting** [comment]
@jvilimek maybe you are active?  

We are planning on making this change and getting it merged upstream to this project.  It'd be beneficial to be in active contact with someone who can guide us and so we can know if its feasible to get an updated Nuget package w/ this change.

**Comment by kirilovskii** [comment]
Hi, sorry for not replying on time!
Just to be clear - I'm not affiliated with Oriflame, so I'm not the best person to communicate with on the project, but I'll try to help. And unfortunately, we end up not using the library in our project due to some limitations.

@twhiting, may I ask what are the planned use cases and the expected load? And whether you plan to do some other changes to the project, except for the config change?

As for the new Nuget package - AFAIK the there is no CI/CD pipeline configured for the project (@frantisekjandos should know more about that) so it would be a good idea to set one up if the library is to be used outside of Oriflame.

**Comment by jvilimek** [comment]
> @jvilimek maybe you are active?
> 
> We are planning on making this change and getting it merged upstream to this project. (if the Oriflame team cannot get to it) It'd be beneficial to be in active contact with someone who can guide us and so we can know if its feasible to get an updated Nuget package w/ this change.

Sorry for not answering earlier. Somehow missed the notification. I will check with the team tomorrow.

**Comment by twhiting** [comment]
@jvilimek no worries! I actually just put up a PR for this. If someone could review that would be great 🙂

**Comment by twhiting** [comment]
@jvilimek this issue can be closed now. Also, would it be too much trouble to update the NuGet feed with this latest version?

**Comment by twhiting** [comment]
I see the NuGet has been updated. Thanks all!

**Comment by frantisekjandos** [comment]
Sorry guys, I had the notifications turned off. I have fixed it ;-)
